<li class="revolution-mch-1" data-transition="fade" data-slotamount="5" data-masterspeed="1000" style="width: 100%; height: 100%; overflow: hidden; visibility: visible; left: 0px; top: 0px; z-index: 18; opacity: 1;">
                <div class="slotholder" style="width:100%;height:100%;" data-duration="undefined" data-zoomstart="undefined" data-zoomend="undefined" data-rotationstart="undefined" data-rotationend="undefined" data-ease="undefined" data-bgpositionend="undefined" data-bgposition="left top" data-kenburns="undefined" data-easeme="undefined" data-bgfit="cover" data-bgfitend="undefined" data-owidth="undefined" data-oheight="undefined"><div class="tp-bgimg defaultimg" data-lazyload="undefined" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" data-lazydone="undefined" src="/img/sliders/LDCE-GEN-NEXT-ARCHITECTURE.jpg" data-src="/img/sliders/LDCE-GEN-NEXT-ARCHITECTURE.jpg" style="background-color: rgba(0, 0, 0, 0); background-repeat: no-repeat; background-image: url(&quot;/img/sliders/LDCE-GEN-NEXT-ARCHITECTURE.jpg&quot;); background-size: cover; background-position: left top; width: 100%; height: 100%; opacity: 0; position: relative;"></div></div>
                <div class="tp-caption tp-caption-bgcolor revolution-ch1 sft start" data-x="left" data-hoffset="0" data-y="367" data-speed="1500" data-start="500" data-easing="Back.easeInOut" data-endeasing="Power1.easeIn" data-endspeed="300" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 47px; border-width: 0px; margin: 0px; padding: 0px 90px; letter-spacing: 0px; font-size: 29px; left: 148px; top: 330.3px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -45, 0, 1);">
                    GEN-NEXT ARCHITECTURE
                </div>

                <div class="tp-caption tp-caption-bgcolor revolution-ch2 sft start" data-x="left" data-hoffset="0" data-y="419" data-speed="1400" data-start="2000" data-easing="Power4.easeOut" data-endspeed="300" data-endeasing="Power1.easeIn" data-captionhidden="off" style="transition: all 0s ease 0s; min-height: 0px; min-width: 0px; line-height: 29px; border-width: 0px; margin: 0px; padding: 0px 90px; letter-spacing: 0px; font-size: 16px; left: 148px; top: 377.1px; visibility: visible; opacity: 0; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, -0.00166, 0, -45, 0, 1);">
                    LDCE’s campus consists of a fine mix of new and modern buildings built with utmost finesse.
                </div>
            </li>